# Generated by Django 4.1.1 on 2022-11-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_biditems_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditems',
            name='actioneer_phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biditems',
            name='auctioneer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
