# Generated by Django 4.1.1 on 2022-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_biditems_minimum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
